check yaml lint

diff --git a/.github/workflows/ci-test2.yml b/.github/workflows/ci-test2.yml
--- a/.github/workflows/ci-test2.yml
+++ b/.github/workflows/ci-test2.yml
@@ -1,6 +1,74 @@
-name: Validate Workflow on PR
+# name: Validate Workflow on PR
+
+# on:
+#   pull_request:
+#     branches:
+#       - main
+#     paths:
+#       - '.github/workflows/**'
+
+# jobs:
+#   validate-workflow:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+      
+#       - name: Install dependencies
+#         run: |
+#             npm install ajv
+#             npm install axios
+#             npm install js-yaml
+#             npm install @actions/core@1.8.0
+
+#       - name: List YAML files to validate
+#         run: |
+#           set -e
+#           files=$(find .github/workflows -name '*.yml')
+#           echo "Validating the following files:"
+#           echo "$files"
+
+
+#       - name: Validate workflow schema
+#         uses: actions/setup-node@v2
+#         with:
+#           node-version: '16.x'
+#           script: |
+#             set -e
+#             const Ajv = require('ajv');
+#             const axios = require('axios');
+#             const yaml = require('js-yaml');
+#             const fs = require('fs').promises;
+
+#             const schema = await axios.get(
+#               'https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json'
+#             );
+
+#             const files = await fs.readdir('.github/workflows');
+#             const ymlFiles = files.filter(file => file.endsWith('.yml'));
+
+#             for (const file of ymlFiles) {
+#               const content = await fs.readFile(`.github/workflows/${file}`, 'utf8');
+#               const target = yaml.load(content);
+
+#               const ajv = new Ajv({ strict: false, allErrors: true });
+#               const validator = ajv.compile(schema.data);
+#               const valid = validator(target);
+#               if (!valid) {
+#                 console.error(`Validation failed with the following errors:`);
+#                 console.error(validator.errors);
+#                 process.exitCode = 1;
+#               } else {
+#                 console.log(`Workflow is valid`);
+#               }
+
+
+
+
+name: YAML Lint
 
 on:
+  
   pull_request:
     branches:
       - main
@@ -8,57 +76,16 @@ on:
       - '.github/workflows/**'
 
 jobs:
-  validate-workflow:
+  yaml-lint:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout Code
         uses: actions/checkout@v2
-      
-      - name: Install dependencies
-        run: |
-            npm install ajv
-            npm install axios
-            npm install js-yaml
-            npm install @actions/core@1.8.0
 
-      - name: List YAML files to validate
+      - name: Install YAML Lint
+        run: npm install -g yaml-lint
+
+      - name: Lint YAML Files
         run: |
           set -e
-          files=$(find .github/workflows -name '*.yml')
-          echo "Validating the following files:"
-          echo "$files"
-
-
-      - name: Validate workflow schema
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16.x'
-          script: |
-            set -e
-            const Ajv = require('ajv');
-            const axios = require('axios');
-            const yaml = require('js-yaml');
-            const fs = require('fs').promises;
-  
-            const schema = await axios.get(
-              'https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json'
-            );
-  
-            const files = await fs.readdir('.github/workflows');
-            const ymlFiles = files.filter(file => file.endsWith('.yml'));
-  
-            for (const file of ymlFiles) {
-              const content = await fs.readFile(`.github/workflows/${file}`, 'utf8');
-              const target = yaml.load(content);
-  
-              const ajv = new Ajv({ strict: false, allErrors: true });
-              const validator = ajv.compile(schema.data);
-              const valid = validator(target);
-              if (!valid) {
-                console.error(`Validation failed with the following errors:`);
-                console.error(validator.errors);
-                process.exitCode = 1;
-              } else {
-                console.log(`Workflow is valid`);
-              }
-  
+          find .github/workflows -type f -name "*.yml" -exec yaml-lint -q {} +
